version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: centrocontrol_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: miPyme
      MYSQL_USER: centrocontrol_user
      MYSQL_PASSWORD: centrocontrol123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - centrocontrol_network
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: centrocontrol_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - centrocontrol_network

volumes:
  mysql_data:
    driver: local

networks:
  centrocontrol_network:
    driver: bridge
